variables:
  REACT_APP_KEYCLOAK_URL: "${KEYCLOAK_URL_PROD}"
  REACT_APP_KEYCLOAK_REALM: "${KEYCLOAK_REALM_PROD}"
  REACT_APP_KEYCLOAK_CLIENT_ID: "${KEYCLOAK_CLIENT_ID_PROD}"
  REACT_APP_API_GATEWAY_BASE_URL: "${API_GATEWAY_BASE_URL_PROD}"
  REACT_APP_URL: "${URL_PROD}"
  REACT_APP_API_KEY: "${API_KEY_PROD}"
  CI: "true"
