## Metadata
## !!! PLEASE DO NOT EDIT THIS FILE IF YOU DON'T KNOW WHAT ARE YOU DOING !!!
## Author: Ilyas Tuyakbayev <ilyas.tuyakbayev@gmail.com>
## Vendor: KazAtomProm JSC
## Base image
FROM reg.kazatomprom.kz/library/kaptechnology/devops/docker-images/nginx:1.20.1-alpine-usiag
## Metadata
LABEL org.opencontainers.image.authors="Ilyas Tuyakbayev <ilyas.tuyakbayev@gmail.com>"
LABEL org.opencontainers.image.vendor="KazAtomProm JSC"
LABEL org.opencontainers.image.title="eKAP React frontend"
LABEL org.opencontainers.image.description="This is a module of eKAP Platform"

## Update nginx config to fix 404 error
RUN sed -i '8s/^/\ttry_files $uri \/index.html;\n/' /etc/nginx/conf.d/default.conf

## Copy application into container
COPY /build/ /usr/share/nginx/html

## Start application
CMD ["nginx", "-g", "daemon off;"]